name: CI
on:
  push:
    branches: main
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/check.yml

  ci-test:
    needs:
      - lint
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Kernel
      uses: ./
      with:
          kernel-url: https://github.com/ZeroTwo-Franxx/android_gki_kernel_5.10_common
          kernel-branch: android12-5.10-2024-05
          config: gki_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: false
          ksu-version: main
          android-version: 12
          aosp-clang-version: 12
          python-27: true
          disable-lto: true
          anykernel3: true
